---
- name: Upgrade apt packages
  apt: upgrade=yes
       update_cache=yes

- name: Install git
  apt: pkg=git

- name: Install NTP
  apt: pkg=ntp

- name: Install ufw
  apt: pkg=ufw

- name: Install Vim
  apt: pkg=vim

- name: Install prerequisite packages that are necessary to compile applications and gems with native extensions
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - build-essential
    - libxslt-dev 
    - libxml2-dev

- name: Install python-software-properties so the apt_repository module will work properly
  apt: pkg=python-software-properties

- name: Install imagemagick
  apt: pkg=imagemagick

- name: Install imagemagick dev
  apt: pkg=libmagickwand-dev
